
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 25 09:08:32 CET 2016
//----------------------------------------------------

package logicline.analyseurs;

/** CUP generated class containing symbol constants. */
public class TypeSymboles {
  /* terminals */
  public static final int OU = 7;
  public static final int IMPL = 8;
  public static final int CO = 16;
  public static final int POINT = 20;
  public static final int AFF = 18;
  public static final int CF = 17;
  public static final int VARIABLE = 2;
  public static final int TRUE = 3;
  public static final int NON = 5;
  public static final int TABLE = 10;
  public static final int PO = 14;
  public static final int EOF = 0;
  public static final int DPLL = 13;
  public static final int VL = 12;
  public static final int VIR = 19;
  public static final int EQUIV = 9;
  public static final int FALSE = 4;
  public static final int ET = 6;
  public static final int error = 1;
  public static final int PF = 15;
  public static final int FNC = 11;
}

